config/routes.rb
Oolsproject::Application.routes.draw do
  resources :taggs
  resources :comment_votes
  resources :post_votes
  resources :comments
  resources :posts
  resources :categories
  resources :users
  resources :sessions

  root :to => 'sessions#new'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "search" => "sessions#show", :as => "search"
  get "sign_up" => "users#new", :as => "sign_up"
  match '/report' => 'posts#report'
  match '/show' => 'sessions#show'
  match ':controller(/:action(/:id(.:format)))'

end

app/models/tagg.rb
class Tagg < ActiveRecord::Base
  belongs_to :post
  attr_accessible :name

  validates_length_of :name, :within => 1..20
  validates_format_of :name, :with => /^[a-zA-Z0-9_]*$/, :message => "Please enter a single word tag"
end

app/controllers/taggs_controller.rb
class TaggsController < ApplicationController
  # GET /taggs
  # GET /taggs.json
  def index
    @taggs = Tagg.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @taggs }
    end
  end

  # GET /taggs/1
  # GET /taggs/1.json
  def show
    @tagg = Tagg.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tagg }
    end
  end

  # GET /taggs/new
  # GET /taggs/new.json
  def new
    @tagg = Tagg.new
    @tagg.post_id = params[:id]
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tagg }
    end
  end

  # GET /taggs/1/edit
  def edit
    @tagg = Tagg.find(params[:id])
  end

  # POST /taggs
  # POST /taggs.json
  def create
    if params["theme"].eql? "Existing Tags"
      @temp = Tagg.find(params[:tagg][:id])
      params[:tagg][:name] = @temp.name
    end

    @tagg = Tagg.new(params[:tagg])
    @tagg.post_id = params["post_id"]
    @post = Post.find(params["post_id"])


    respond_to do |format|
      @arr = Tagg.where( "post_id = ? AND name = ?", params["post_id"], params[:tagg][:name] )
      if @arr.empty?
        if @tagg.save
          format.html { redirect_to @post, notice: 'Tag was successfully created.' }
          format.json { render json: @post, status: :created, location: @post }
        else
          format.html { render action: "new" }
          format.json { render json: @tagg.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to @post, notice: 'Tag already exists.' }
        format.json { render json: @post, status: :created, location: @post }
      end
    end
  end

  # PUT /taggs/1
  # PUT /taggs/1.json
  def update
    @tagg = Tagg.find(params[:id])

    respond_to do |format|
      if @tagg.update_attributes(params[:tagg])
        format.html { redirect_to @tagg, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tagg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taggs/1
  # DELETE /taggs/1.json
  def destroy
    @tagg = Tagg.find(params[:id])
    @tagg.destroy

    respond_to do |format|
      format.html { redirect_to taggs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/taggs_helper.rb
module TaggsHelper
end

app/views/taggs/_form.html.erb
<%= form_for(@tagg) do |f| %>
  <% if @tagg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tagg.errors.count, "error") %> prohibited this tagg from being saved:</h2>

      <ul>
      <% @tagg.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <table width =50%>
      <tr align = left>
        <td>
          <div class="form_row">
            <label for="theme">Select:</label>
            <% [ 'Existing Tags', 'New Tag' ].each do |theme| %>
                <br><%= radio_button_tag 'theme', theme, @theme == theme, :checked => 1 %>
                <%= theme.humanize %>
            <% end %>
          </div>
        </td>
        <td>
          <br></br>

          <%arr = Tagg.find(:all)%>
          <%tempx =  Array.new%>
          <%tempy = Array.new%>
          <%arr.each do |val|%>
              <%  if !tempx.include? val.name%>
                  <%tempx << val.name%>
                  <%tempy << val%>
              <%  end%>
          <%end%>

          <%= select("tagg", "id", tempy.collect{ |c| [ c.name, c.id] }) %>
          <br><%= f.text_field :name %></br>

        </td>
      </tr>
    </table>
     </br>
    <div class="actions">
      <%= f.submit "Add Tag" %>
    </div>

    <%= hidden_field_tag('post_id',@post.id) %>

<% end %>

app/views/taggs/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tagg %> |
<%= link_to 'Back', taggs_path %>

app/views/taggs/index.html.erb
<h2>Listing Tags</h2>
</br>
<table border ="true">
  <tr align="left" bgcolor = "#c8860b">
    <th>Name</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @taggs.each do |tagg| %>
  <tr>
    <td><%= tagg.name %></td>
    <td><%= tagg.post %></td>
    <td><%= link_to 'Show', tagg %></td>
    <td><%= link_to 'Edit', edit_tagg_path(tagg) %></td>
    <td><%= link_to 'Destroy', tagg, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tagg', new_tagg_path %>

app/views/taggs/new.html.erb
<h1>Add Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/taggs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tagg.name %>
</p>

<p>
  <b>Post:</b>
  <%= @tagg.post %>
</p>


<%= link_to 'Edit', edit_tagg_path(@tagg) %> |
<%= link_to 'Back', taggs_path %>