config/routes.rb
Oolsproject::Application.routes.draw do
  resources :taggs
  resources :comment_votes
  resources :post_votes
  resources :comments
  resources :posts
  resources :categories
  resources :users
  resources :sessions

  root :to => 'sessions#new'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "search" => "sessions#show", :as => "search"
  get "sign_up" => "users#new", :as => "sign_up"
  match '/report' => 'posts#report'
  match '/show' => 'sessions#show'
  match ':controller(/:action(/:id(.:format)))'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :comments, :dependent => :destroy
  has_many :post_votes, :dependent => :destroy
  has_many :taggs

  attr_accessible :description, :title, :category, :category_id

  validates :title, :presence => true
  validates :description, :presence => true
  validates :user, :presence => true
  validates :category, :presence => true

  def self.is_owner?(post, user)
    some_post = Post.where("id = ? and user_id = ?",post, user)
    if some_post.empty?
      false
    else
      true
    end
  end

  def self.search_by_user(search)
    search_condition = "%" + search + "%"
    find_user = User.where("email like ? OR name like ?",search_condition, search_condition)
    result = find(:all, :conditions => ['1=2'])
    for i in find_user do
      result = result + find(:all, :conditions => ['user_id = ?', i.id])
    end
    return result
  end

  def self.search_by_category(search)
    search_condition = "%" + search + "%"
    find_category = Category.where("category like ?",search_condition)
    result = find(:all, :conditions => ['1=2'])
    for i in find_category do
      result = result + find(:all, :conditions => ['category_id = ?', i.id])
    end
    return result
  end

  def self.search_by_content(search)
    search_condition = "%" + search + "%"
    find(:all, :conditions => ['title LIKE ? OR description LIKE ?', search_condition,search_condition])
  end


  def self.search_by_tag(search)
    search_condition = "%" + search + "%"
    find_tag = Tagg.where("name LIKE ?",search_condition)
    result = find(:all, :conditions => ['1=2'])
    for i in find_tag do
      result = result+find(:all, :conditions => ['id = ?', i.post_id])
    end
    return result
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all(:order => 'updated_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @vote_post = PostVote.where("post_id = ?",params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end


  def record_votes
    @post = Post.find(params[:id])
    uname = current_user
    some_vote = PostVote.where("post_id = ? and user_id = ?",params[:id], uname.id)

    if some_vote.empty?
      PostVote.record_one_vote(params[:id], uname.id)

      #to order the posts according to latest comment activity
      @post.updated_at = Time.now
      @post.save!
      flash[:login_error] = "Thank you for voting for the post."
    else
      flash[:login_error] = "Your vote for post is already registered."
    end
    redirect_to @post
  end

  def record_comment_votes
    @post = Post.find(params[:post_id])
    uname = current_user
    some_vote = CommentVote.where("comment_id = ? and user_id = ?",params[:id], uname.id)

    if some_vote.empty?
      CommentVote.record_one_vote(params[:id], uname.id)

      #to order the posts according to latest comment activity
      @post.updated_at = Time.now
      @post.save!
      flash[:login_error] = "Thank you for voting for the comment."
    else
      flash[:login_error] = "Your vote on comment is already registered."

    end
    redirect_to @post
  end

  def report
    @posts = Post.all
  end

  # shows posts when no user is logged in
  def show_posts_unlogged
    @post = Post.find(params[:id])
    @vote_post = PostVote.where("post_id = ?",params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :category %>
      <%= select("post", "category_id", Category.where("category != ?","anonymous").collect{ |c| [ c.category, c.id] }) %>
    </div>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h2>Posts</h2>
</br>
<table border="true">
  <tr align=left bgcolor = "#c8860b">
    <th width="10%">Title</th>
    <th width="5%">Category</th>
    <th width="30%">Description</th>
    <th width="10%">Tags</th>
    <th width="10%">User</th>
    <th colspan="3" width ="10%">Actions</th>
  </tr>

  <% @posts.each do |post| %>
      <tr>
        <td><%= link_to h(post.title), post_path(post.id) %></td>
        <td><%= post.category.category %></td>
        <td><%= post.description %></td>
        <td>
        <% post.taggs.each do |tagg| %>
            <%= tagg.name %>
        <% end%>
        </td>
        <td><%= post.user.email %></td>
        <% @pid=post.id %>

        <% if current_user and (User.is_Admin?(current_user.id) or Post.is_owner?(post.id,current_user.id))  %>
            <td><%= link_to 'Add a tag', :controller => 'taggs',:action => 'new',:id=> @pid %></td>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>     <% end%>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'Create New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/record_comment_votes.erb
<h1> Thanks for Voting for comment! </h1>

app/views/posts/record_votes.html.erb
<h1> Thank you! </h1>

app/views/posts/report.html.erb
<h2>Post Activity Report</h2>
</br>
<table border="true" width="100%">
  <tr align=left bgcolor = "#c8860b">
    <th width="20%">Title</th>
    <th width="10%">Category</th>
    <th width="40%">Description</th>
    <th width="10%">User</th>
    <th width="10%"> Total Comments </th>
    <th width="10%"> Total Votes for Post </th>

  </tr>

  <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.category.category %></td>
        <td><%= post.description %></td>
        <td><%= post.user.email %></td>
        <td><%= post.comments.count %></td>
        <td><%= post.post_votes.count %></td>
      </tr>
  <% end %>
</table>

<br />


app/views/posts/show.html.erb
<%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
<% end %>
<p></p>
</br>
<table border="true">
  <tr align=left >
    <td bgcolor="#c8860b"><b>Category</b></td>
    <td><%= @post.category.category %></td>
  </tr>
  <tr align=left>
    <td bgcolor="#c8860b"><b>Email</b></td>
    <td><%= @post.user.email %></td>
  </tr>
  <tr align=left >
    <td bgcolor="#c8860b"><b>Title</b></td>
    <td><%= @post.title %></td>
  </tr>
  <tr align=left >
    <td bgcolor="#c8860b"><b>Description</b></td>
    <td><%= @post.description %></td>
  </tr>
  <tr align=left >
    <td bgcolor="#c8860b"><b>Tags</b></td>
    <td><% for tagg in @post.taggs %>
          <%= tagg.name %>
      <% end %></td>
  </tr>
  <tr align=left>
    <td bgcolor="#c8860b"><b>Votes</b></td>
    <% total_post_votes = @vote_post.count %>
    <td> <% if has_user_voted_on_post?(@post.id)  %>
          <% if total_post_votes == 1 %>
              You Voted
          <% else %>
              You and <%= link_to h(total_post_votes-1),post_vote_path %> other people voted
          <% end %>
      <% else %>
          <% if total_post_votes == 0 %>
              0 Votes
          <% else %>
              <%= link_to h(total_post_votes), post_vote_path %> people voted
          <% end %>
      <% end %>

      <% if PostVote.has_voted?(@post.id,current_user.id) or Post.is_owner?(@post.id,current_user.id) %>
      <% else %>
          <%= button_to "Vote Post", :action => 'record_votes', :id => @post.id %>
      <% end %></td>
  </tr>
</table>
<p></p>
</br>

<table width=100% border="true">
  <tr align=left bgcolor="#c8860b">
    <th>comment</th>
    <th>by user</th>
    <th>when?</th>
    <th>Votes</th>
    <th colspan="3" width ="10%">Actions</th>
  </tr>
  <% i=0 %>
  <% for comment in @post.comments %>
      <tr>
        <td><%= comment.description %></td>
        <td><%= comment.user.email %></td>
        <td><%= distance_of_time_in_words_to_now comment.created_at %> ago</td>
        <% total_votes = comment.comment_votes.count %>
        <td><% if has_user_voted_on_comment?(comment.id)  %>
              <% if total_votes == 1 %>
                  You voted
              <% else %>
                  You and <%= link_to h(total_votes-1), :controller => "comment_votes", :action => "show", :id => comment.id %> other people voted
              <% end %>
          <% else %>
              <% if total_votes == 0 %>
                  0 Votes
              <% else %>
                  <%= link_to h(total_votes),  :controller => "comment_votes", :action => "show", :id => comment.id %> people voted
              <% end %>
          <% end %></td>
        <% if CommentVote.has_voted?(comment.id, current_user.id) or Comment.is_owner?(comment.id, current_user.id)%>
            <td> </td>
        <% else %>
            <td><%= button_to "Vote Comment" , :action => 'record_comment_votes', :id => comment.id, :post_id => @post.id %></td>
        <% end %>
        <% if current_user and (User.is_Admin?(current_user.id) or Comment.is_owner?(comment.id,current_user.id))  %>
            <td><%= link_to "Edit", edit_comment_path(comment) %></td>
            <td><%= link_to "Destroy", comment, :confirm => 'Are you sure?', :method => :delete %></td>            <% end %>
      </tr>
  <% end %>
</table>


</br>
<% if current_user and (User.is_Admin?(current_user.id) or Post.is_owner?(@post.id,current_user.id))  %>
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Add Tag', :controller => 'taggs' , :action => 'new', :id => @post.id %> |
<% end %>
<% if current_user %>
    <%= link_to 'Add Comment', :controller => 'comments' , :action => 'new', :id => @post.id %> |
<% end %>
<%= link_to 'Back', posts_url %>
<td class="right"></td>

app/views/posts/show_posts_unlogged.html.erb
<p>
  <b>Category:</b>
  <%= @post.category.category %>
</p>

<p>
  <b>Username (email):</b>
  <%= @post.user.email %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Description:</b>
  <%= @post.description %>
</p>

<p>
  <b>Tags:</b>
  <% for tagg in @post.taggs %>
      <%= tagg.name %>
  <% end %>
</p>

<p>
  <b>Votes:</b>
  <%= @vote_post.count %>
</p>

</p>
<table  border="true">
  <tr align=left>
    <th>comment</th>
    <th>by user</th>
    <th>when?</th>
    <th>Votes</th>
  </tr>
  <% i=0 %>
  <% for comment in @post.comments %>
      <tr>
        <td><%= comment.description %></td>
        <td><%= comment.user.email %></td>
        <td><%= distance_of_time_in_words_to_now comment.created_at %> ago</td>
        <td><%= comment.comment_votes.count %>
      </tr>
  <% end %>
</table>

<%= link_to 'Back', search_path %>
