config/routes.rb
Oolsproject::Application.routes.draw do
  resources :taggs
  resources :comment_votes
  resources :post_votes
  resources :comments
  resources :posts
  resources :categories
  resources :users
  resources :sessions

  root :to => 'sessions#new'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "search" => "sessions#show", :as => "search"
  get "sign_up" => "users#new", :as => "sign_up"
  match '/report' => 'posts#report'
  match '/show' => 'sessions#show'
  match ':controller(/:action(/:id(.:format)))'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :category
  has_many :posts
  validates :category, :presence => true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      #checks to disallow naming a category as anonymous
      if @category.category =~ /^anonymous$/i
        @category.errors.add(:category,"-anonymous is a reserved category")
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      else
        if @category.save
          format.html { redirect_to @category, notice: 'Category was successfully created.' }
          format.json { render json: @category, status: :created, location: @category }
        else
          format.html { render action: "new" }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    anon = Category.find_by_category("anonymous")

    ###### Update related Posts ######
    temp = Post.find_all_by_category_id(@category.id)
    temp.each do |post|
      post.category_id = anon.id
      post.save
    end
    respond_to do |format|
      if @category.destroy
        format.html { redirect_to categories_path, notice: 'Category was successfully deleted.' }
        format.json { head :no_content }
      else
        format.html { redirect_to categories_path, notice: "-Category couldn't be deleted." }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h2>Categories</h2>
</br>
<table border ="true" width="40%">
  <tr align ="left"  bgcolor = "#c8860b">
    <th>Category</th>
    <th colspan="3" >Actions</th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.category %></td>
    <td><%= link_to 'Show', category %></td>
    <% if category.category != "anonymous" %>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Create New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <b>Category:</b>
  <%= @category.category %>
</p>


<table border="true">
  <tr align ="left" bgcolor="#c8860b">
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>


  <% @category.posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>